package org.dandj.api;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: API.proto

public final class API {
  private API() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CellOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Cell)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>required int32 y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code Cell}
   */
  public static final class Cell extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Cell)
      CellOrBuilder {
    // Use Cell.newBuilder() to construct.
    private Cell(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Cell(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }
    public Region parent;
    private static final Cell defaultInstance;
    public static Cell getDefaultInstance() {
      return defaultInstance;
    }

    public Cell getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Cell(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return API.internal_static_Cell_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return API.internal_static_Cell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              API.Cell.class, API.Cell.Builder.class);
    }

    public static com.google.protobuf.Parser<Cell> PARSER =
        new com.google.protobuf.AbstractParser<Cell>() {
      public Cell parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cell(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Cell> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required int32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required int32 y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static API.Cell parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static API.Cell parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static API.Cell parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static API.Cell parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static API.Cell parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static API.Cell parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static API.Cell parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static API.Cell parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static API.Cell parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static API.Cell parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(API.Cell prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cell}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Cell)
        API.CellOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return API.internal_static_Cell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return API.internal_static_Cell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                API.Cell.class, API.Cell.Builder.class);
      }

      // Construct using API.Cell.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return API.internal_static_Cell_descriptor;
      }

      public API.Cell getDefaultInstanceForType() {
        return API.Cell.getDefaultInstance();
      }

      public API.Cell build() {
        API.Cell result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public API.Cell buildPartial() {
        API.Cell result = new API.Cell(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof API.Cell) {
          return mergeFrom((API.Cell)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(API.Cell other) {
        if (other == API.Cell.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        API.Cell parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (API.Cell) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Cell)
    }

    static {
      defaultInstance = new Cell(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Cell)
  }

  public interface RegionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Region)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    java.util.List<API.Cell> 
        getCellsList();
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    API.Cell getCells(int index);
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    int getCellsCount();
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    java.util.List<? extends API.CellOrBuilder> 
        getCellsOrBuilderList();
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    API.CellOrBuilder getCellsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Region}
   */
  public static final class Region extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Region)
      RegionOrBuilder {
    // Use Region.newBuilder() to construct.
    private Region(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Region(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Region defaultInstance;
    public static Region getDefaultInstance() {
      return defaultInstance;
    }

    public Region getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Region(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cells_ = new java.util.ArrayList<API.Cell>();
                mutable_bitField0_ |= 0x00000001;
              }
              cells_.add(input.readMessage(API.Cell.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return API.internal_static_Region_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return API.internal_static_Region_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              API.Region.class, API.Region.Builder.class);
    }

    public static com.google.protobuf.Parser<Region> PARSER =
        new com.google.protobuf.AbstractParser<Region>() {
      public Region parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Region(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Region> getParserForType() {
      return PARSER;
    }

    public static final int CELLS_FIELD_NUMBER = 1;
    private java.util.List<API.Cell> cells_;
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    public java.util.List<API.Cell> getCellsList() {
      return cells_;
    }
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    public java.util.List<? extends API.CellOrBuilder> 
        getCellsOrBuilderList() {
      return cells_;
    }
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    public int getCellsCount() {
      return cells_.size();
    }
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    public API.Cell getCells(int index) {
      return cells_.get(index);
    }
    /**
     * <code>repeated .Cell cells = 1;</code>
     */
    public API.CellOrBuilder getCellsOrBuilder(
        int index) {
      return cells_.get(index);
    }

    private void initFields() {
      cells_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCellsCount(); i++) {
        if (!getCells(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < cells_.size(); i++) {
        output.writeMessage(1, cells_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cells_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cells_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static API.Region parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static API.Region parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static API.Region parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static API.Region parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static API.Region parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static API.Region parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static API.Region parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static API.Region parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static API.Region parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static API.Region parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(API.Region prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Region}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Region)
        API.RegionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return API.internal_static_Region_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return API.internal_static_Region_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                API.Region.class, API.Region.Builder.class);
      }

      // Construct using API.Region.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCellsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return API.internal_static_Region_descriptor;
      }

      public API.Region getDefaultInstanceForType() {
        return API.Region.getDefaultInstance();
      }

      public API.Region build() {
        API.Region result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public API.Region buildPartial() {
        API.Region result = new API.Region(this);
        int from_bitField0_ = bitField0_;
        if (cellsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            cells_ = java.util.Collections.unmodifiableList(cells_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cells_ = cells_;
        } else {
          result.cells_ = cellsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof API.Region) {
          return mergeFrom((API.Region)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(API.Region other) {
        if (other == API.Region.getDefaultInstance()) return this;
        if (cellsBuilder_ == null) {
          if (!other.cells_.isEmpty()) {
            if (cells_.isEmpty()) {
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCellsIsMutable();
              cells_.addAll(other.cells_);
            }
            onChanged();
          }
        } else {
          if (!other.cells_.isEmpty()) {
            if (cellsBuilder_.isEmpty()) {
              cellsBuilder_.dispose();
              cellsBuilder_ = null;
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cellsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCellsFieldBuilder() : null;
            } else {
              cellsBuilder_.addAllMessages(other.cells_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCellsCount(); i++) {
          if (!getCells(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        API.Region parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (API.Region) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<API.Cell> cells_ =
        java.util.Collections.emptyList();
      private void ensureCellsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cells_ = new java.util.ArrayList<API.Cell>(cells_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          API.Cell, API.Cell.Builder, API.CellOrBuilder> cellsBuilder_;

      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public java.util.List<API.Cell> getCellsList() {
        if (cellsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cells_);
        } else {
          return cellsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public int getCellsCount() {
        if (cellsBuilder_ == null) {
          return cells_.size();
        } else {
          return cellsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public API.Cell getCells(int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);
        } else {
          return cellsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder setCells(
          int index, API.Cell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.set(index, value);
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder setCells(
          int index, API.Cell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.set(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder addCells(API.Cell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder addCells(
          int index, API.Cell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(index, value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder addCells(
          API.Cell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder addCells(
          int index, API.Cell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder addAllCells(
          java.lang.Iterable<? extends API.Cell> values) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cells_);
          onChanged();
        } else {
          cellsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder clearCells() {
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public Builder removeCells(int index) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.remove(index);
          onChanged();
        } else {
          cellsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public API.Cell.Builder getCellsBuilder(
          int index) {
        return getCellsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public API.CellOrBuilder getCellsOrBuilder(
          int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);  } else {
          return cellsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public java.util.List<? extends API.CellOrBuilder> 
           getCellsOrBuilderList() {
        if (cellsBuilder_ != null) {
          return cellsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cells_);
        }
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public API.Cell.Builder addCellsBuilder() {
        return getCellsFieldBuilder().addBuilder(
            API.Cell.getDefaultInstance());
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public API.Cell.Builder addCellsBuilder(
          int index) {
        return getCellsFieldBuilder().addBuilder(
            index, API.Cell.getDefaultInstance());
      }
      /**
       * <code>repeated .Cell cells = 1;</code>
       */
      public java.util.List<API.Cell.Builder> 
           getCellsBuilderList() {
        return getCellsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          API.Cell, API.Cell.Builder, API.CellOrBuilder> 
          getCellsFieldBuilder() {
        if (cellsBuilder_ == null) {
          cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              API.Cell, API.Cell.Builder, API.CellOrBuilder>(
                  cells_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          cells_ = null;
        }
        return cellsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Region)
    }

    static {
      defaultInstance = new Region(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Region)
  }

  public interface StageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Stage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 resolution = 1;</code>
     */
    boolean hasResolution();
    /**
     * <code>required int32 resolution = 1;</code>
     */
    int getResolution();

    /**
     * <code>required int32 width = 2;</code>
     */
    boolean hasWidth();
    /**
     * <code>required int32 width = 2;</code>
     */
    int getWidth();

    /**
     * <code>required int32 height = 3;</code>
     */
    boolean hasHeight();
    /**
     * <code>required int32 height = 3;</code>
     */
    int getHeight();

    /**
     * <code>repeated .Region regions = 5;</code>
     */
    java.util.List<API.Region> 
        getRegionsList();
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    API.Region getRegions(int index);
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    int getRegionsCount();
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    java.util.List<? extends API.RegionOrBuilder> 
        getRegionsOrBuilderList();
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    API.RegionOrBuilder getRegionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Stage}
   */
  public static final class Stage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Stage)
      StageOrBuilder {
    // Use Stage.newBuilder() to construct.
    private Stage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Stage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Stage defaultInstance;
    public static Stage getDefaultInstance() {
      return defaultInstance;
    }

    public Stage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Stage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resolution_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              width_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              height_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                regions_ = new java.util.ArrayList<API.Region>();
                mutable_bitField0_ |= 0x00000008;
              }
              regions_.add(input.readMessage(API.Region.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          regions_ = java.util.Collections.unmodifiableList(regions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return API.internal_static_Stage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return API.internal_static_Stage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              API.Stage.class, API.Stage.Builder.class);
    }

    public static com.google.protobuf.Parser<Stage> PARSER =
        new com.google.protobuf.AbstractParser<Stage>() {
      public Stage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Stage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESOLUTION_FIELD_NUMBER = 1;
    private int resolution_;
    /**
     * <code>required int32 resolution = 1;</code>
     */
    public boolean hasResolution() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 resolution = 1;</code>
     */
    public int getResolution() {
      return resolution_;
    }

    public static final int WIDTH_FIELD_NUMBER = 2;
    private int width_;
    /**
     * <code>required int32 width = 2;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 width = 2;</code>
     */
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <code>required int32 height = 3;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 height = 3;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int REGIONS_FIELD_NUMBER = 5;
    private java.util.List<API.Region> regions_;
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    public java.util.List<API.Region> getRegionsList() {
      return regions_;
    }
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    public java.util.List<? extends API.RegionOrBuilder> 
        getRegionsOrBuilderList() {
      return regions_;
    }
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    public int getRegionsCount() {
      return regions_.size();
    }
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    public API.Region getRegions(int index) {
      return regions_.get(index);
    }
    /**
     * <code>repeated .Region regions = 5;</code>
     */
    public API.RegionOrBuilder getRegionsOrBuilder(
        int index) {
      return regions_.get(index);
    }

    private void initFields() {
      resolution_ = 0;
      width_ = 0;
      height_ = 0;
      regions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResolution()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRegionsCount(); i++) {
        if (!getRegions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resolution_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, width_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, height_);
      }
      for (int i = 0; i < regions_.size(); i++) {
        output.writeMessage(5, regions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resolution_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, width_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, height_);
      }
      for (int i = 0; i < regions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, regions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static API.Stage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static API.Stage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static API.Stage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static API.Stage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static API.Stage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static API.Stage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static API.Stage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static API.Stage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static API.Stage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static API.Stage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(API.Stage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Stage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Stage)
        API.StageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return API.internal_static_Stage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return API.internal_static_Stage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                API.Stage.class, API.Stage.Builder.class);
      }

      // Construct using API.Stage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRegionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resolution_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (regionsBuilder_ == null) {
          regions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          regionsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return API.internal_static_Stage_descriptor;
      }

      public API.Stage getDefaultInstanceForType() {
        return API.Stage.getDefaultInstance();
      }

      public API.Stage build() {
        API.Stage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public API.Stage buildPartial() {
        API.Stage result = new API.Stage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resolution_ = resolution_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.height_ = height_;
        if (regionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            regions_ = java.util.Collections.unmodifiableList(regions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.regions_ = regions_;
        } else {
          result.regions_ = regionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof API.Stage) {
          return mergeFrom((API.Stage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(API.Stage other) {
        if (other == API.Stage.getDefaultInstance()) return this;
        if (other.hasResolution()) {
          setResolution(other.getResolution());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (regionsBuilder_ == null) {
          if (!other.regions_.isEmpty()) {
            if (regions_.isEmpty()) {
              regions_ = other.regions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureRegionsIsMutable();
              regions_.addAll(other.regions_);
            }
            onChanged();
          }
        } else {
          if (!other.regions_.isEmpty()) {
            if (regionsBuilder_.isEmpty()) {
              regionsBuilder_.dispose();
              regionsBuilder_ = null;
              regions_ = other.regions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              regionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRegionsFieldBuilder() : null;
            } else {
              regionsBuilder_.addAllMessages(other.regions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResolution()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        for (int i = 0; i < getRegionsCount(); i++) {
          if (!getRegions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        API.Stage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (API.Stage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int resolution_ ;
      /**
       * <code>required int32 resolution = 1;</code>
       */
      public boolean hasResolution() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 resolution = 1;</code>
       */
      public int getResolution() {
        return resolution_;
      }
      /**
       * <code>required int32 resolution = 1;</code>
       */
      public Builder setResolution(int value) {
        bitField0_ |= 0x00000001;
        resolution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 resolution = 1;</code>
       */
      public Builder clearResolution() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resolution_ = 0;
        onChanged();
        return this;
      }

      private int width_ ;
      /**
       * <code>required int32 width = 2;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 width = 2;</code>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <code>required int32 width = 2;</code>
       */
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000002;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 width = 2;</code>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>required int32 height = 3;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 height = 3;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>required int32 height = 3;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000004;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 height = 3;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<API.Region> regions_ =
        java.util.Collections.emptyList();
      private void ensureRegionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          regions_ = new java.util.ArrayList<API.Region>(regions_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          API.Region, API.Region.Builder, API.RegionOrBuilder> regionsBuilder_;

      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public java.util.List<API.Region> getRegionsList() {
        if (regionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(regions_);
        } else {
          return regionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public int getRegionsCount() {
        if (regionsBuilder_ == null) {
          return regions_.size();
        } else {
          return regionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public API.Region getRegions(int index) {
        if (regionsBuilder_ == null) {
          return regions_.get(index);
        } else {
          return regionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder setRegions(
          int index, API.Region value) {
        if (regionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegionsIsMutable();
          regions_.set(index, value);
          onChanged();
        } else {
          regionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder setRegions(
          int index, API.Region.Builder builderForValue) {
        if (regionsBuilder_ == null) {
          ensureRegionsIsMutable();
          regions_.set(index, builderForValue.build());
          onChanged();
        } else {
          regionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder addRegions(API.Region value) {
        if (regionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegionsIsMutable();
          regions_.add(value);
          onChanged();
        } else {
          regionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder addRegions(
          int index, API.Region value) {
        if (regionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegionsIsMutable();
          regions_.add(index, value);
          onChanged();
        } else {
          regionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder addRegions(
          API.Region.Builder builderForValue) {
        if (regionsBuilder_ == null) {
          ensureRegionsIsMutable();
          regions_.add(builderForValue.build());
          onChanged();
        } else {
          regionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder addRegions(
          int index, API.Region.Builder builderForValue) {
        if (regionsBuilder_ == null) {
          ensureRegionsIsMutable();
          regions_.add(index, builderForValue.build());
          onChanged();
        } else {
          regionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder addAllRegions(
          java.lang.Iterable<? extends API.Region> values) {
        if (regionsBuilder_ == null) {
          ensureRegionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, regions_);
          onChanged();
        } else {
          regionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder clearRegions() {
        if (regionsBuilder_ == null) {
          regions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          regionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public Builder removeRegions(int index) {
        if (regionsBuilder_ == null) {
          ensureRegionsIsMutable();
          regions_.remove(index);
          onChanged();
        } else {
          regionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public API.Region.Builder getRegionsBuilder(
          int index) {
        return getRegionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public API.RegionOrBuilder getRegionsOrBuilder(
          int index) {
        if (regionsBuilder_ == null) {
          return regions_.get(index);  } else {
          return regionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public java.util.List<? extends API.RegionOrBuilder> 
           getRegionsOrBuilderList() {
        if (regionsBuilder_ != null) {
          return regionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(regions_);
        }
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public API.Region.Builder addRegionsBuilder() {
        return getRegionsFieldBuilder().addBuilder(
            API.Region.getDefaultInstance());
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public API.Region.Builder addRegionsBuilder(
          int index) {
        return getRegionsFieldBuilder().addBuilder(
            index, API.Region.getDefaultInstance());
      }
      /**
       * <code>repeated .Region regions = 5;</code>
       */
      public java.util.List<API.Region.Builder> 
           getRegionsBuilderList() {
        return getRegionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          API.Region, API.Region.Builder, API.RegionOrBuilder> 
          getRegionsFieldBuilder() {
        if (regionsBuilder_ == null) {
          regionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              API.Region, API.Region.Builder, API.RegionOrBuilder>(
                  regions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          regions_ = null;
        }
        return regionsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Stage)
    }

    static {
      defaultInstance = new Stage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Stage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Cell_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cell_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Region_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Region_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Stage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Stage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tAPI.proto\"\034\n\004Cell\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(" +
      "\005\"\036\n\006Region\022\024\n\005cells\030\001 \003(\0132\005.Cell\"T\n\005Sta" +
      "ge\022\022\n\nresolution\030\001 \002(\005\022\r\n\005width\030\002 \002(\005\022\016\n" +
      "\006height\030\003 \002(\005\022\030\n\007regions\030\005 \003(\0132\007.Region"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Cell_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Cell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Cell_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_Region_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Region_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Region_descriptor,
        new java.lang.String[] { "Cells", });
    internal_static_Stage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Stage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Stage_descriptor,
        new java.lang.String[] { "Resolution", "Width", "Height", "Regions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
